# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
