# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0002_part_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('part_number', models.CharField(max_length=20)),
                ('location', models.CharField(blank=True, max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.Transaction')),
            ],
        ),
        migrations.RemoveField(
            model_name='part',
            name='transaction',
        ),
        migrations.DeleteModel(
            name='Part',
        ),
    ]
