# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 22:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0004_transaction_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='users',
            new_name='user',
        ),
    ]
