# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.CharField(max_length=2)),
                ('confirmed', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=75)),
                ('confirmed', models.BooleanField(default=True)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.Kit')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('step_text', models.TextField()),
                ('confirmed', models.BooleanField(default=True)),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('date_verified', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('I', 'Incomplete'), ('S', 'Started'), ('B', 'Blocked'), ('C', 'Completed'), ('V', 'Verified')], default='I', max_length=1)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.Page')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.Section'),
        ),
    ]
