# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 05:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step_Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_created', models.DateField()),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='step',
            name='notes',
        ),
        migrations.AddField(
            model_name='step_note',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.Step'),
        ),
    ]
