# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 06:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_auto_20170116_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step_note',
            old_name='creator',
            new_name='user',
        ),
    ]
